version: '3.8'
services:
  backend:
    build: ./server
    container_name: q-res-backend
    ports:
      - "8081:8081"
    depends_on:
      - database
    environment:
      - DATABASE_URL=mongodb://database:27017/quickreserve

  database:
    image: mongo:latest
    container_name: q-res-db
    ports:
      - "27017:27017"
    volumes:
      - q_res_data:/data/db

  frontend:
    build: ./client
    container_name: q-res-frontend
    ports:
      - "5173:5173"

volumes:
  q_res_data: